name: Run NonoDailyCardGame

on:
  schedule:
    - cron: '0 6 * * ?'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build and run NonoCardGame
      run:  |
        cd NonoDailyCardGame/NonoDailyCardGame/
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet run your_email your_password
        
